# Generated by Django 5.0.6 on 2024-06-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrier_provider_vehicle_product_stock_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
