# Generated by Django 5.0.6 on 2024-06-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_product_delete_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
