# Generated by Django 5.0.6 on 2024-06-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrier',
        ),
    ]
