# Generated by Django 5.0.6 on 2024-07-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_carrier'),
        ('core', '0007_product_image'),
    ]

    operations = [
    ]
