<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-07-02 18:58
=======
>>>>>>> master

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_carrier'),
        ('core', '0007_product_image'),
    ]

    operations = [
    ]
