# Generated by Django 5.0.4 on 2024-07-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrier',
        ),
        migrations.AddField(
            model_name='customer',
            name='password1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
