# Generated by Django 5.0.4 on 2024-07-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
