from django.urls import path
from .views import *

urlpatterns = [
    path('', root),
    path('producto/', producto_lista, name="producto"),    
    path('producto/<str:producto_id>/delete', producto_delete, name="producto-delete"),
    path('producto/detail/<str:producto_id>', producto_detail, name="producto-detail"),
    path('producto/edit/<str:producto_id>', producto_update, name="producto-edit"),
    path('producto/new/', producto_new, name="producto-new"),
    path('producto/proveedor/<proveedor>', producto_by_proveedor, name="producto-proveedor"),
    path('producto/tipo/<tipo>',producto_by_tipo, name="producto-tipo"),
    path('tipoProducto/', tipoProducto_lista, name="tipoProducto"), 
    path('tipoProducto/<str:tipoProducto_id>/delete', tipoProducto_delete, name="tipoProducto-delete"),
    path('tipoProducto/detail/<str:tipoProducto_id>', tipoProducto_detail, name="tipoProducto-detail"),
    path('tipoProducto/edit/<str:tipoProducto_id>', tipoProducto_update, name="tipoProducto-edit"),
    path('tipoProducto/new/', tipoProducto_new, name="tipoProducto-new"),
    path('proveedor/', proveedor_lista, name="proveedor"), 
    path('proveedor/<str:proveedor_id>/delete', proveedor_delete, name="proveedor-delete"),
    path('proveedor/detail/<str:proveedor_id>', proveedor_detail, name="proveedor-detail"),
    path('proveedor/edit/<str:proveedor_id>', proveedor_update, name="proveedor-edit"),
    path('proveedor/new/', proveedor_new, name="proveedor-new"),
    path('tipoVehiculo/', tipoVehiculo_lista, name="tipoVehiculo"), 
    path('tipoVehiculo/<str:tipoVehiculo_id>/delete', tipoVehiculo_delete, name="tipoVehiculo-delete"),
    path('tipoVehiculo/detail/<str:tipoVehiculo_id>', tipoVehiculo_detail, name="tipoVehiculo-detail"),
    path('tipoVehiculo/edit/<str:tipoVehiculo_id>', tipoVehiculo_update, name="tipoVehiculo-edit"),
    path('tipoVehiculo/new/', tipoVehiculo_new, name="tipoVehiculo-new"),
    path('estadoVehiculo/', estadoVehiculo_lista, name="estadoVehiculo"), 
    path('estadoVehiculo/<str:estadoVehiculo_id>/delete', estadoVehiculo_delete, name="estadoVehiculo-delete"),
    path('estadoVehiculo/detail/<str:estadoVehiculo_id>', estadoVehiculo_detail, name="estadoVehiculo-detail"),
    path('estadoVehiculo/edit/<str:estadoVehiculo_id>', estadoVehiculo_update, name="estadoVehiculo-edit"),
    path('estadoVehiculo/new/', estadoVehiculo_new, name="estadoVehiculo-new"),
]