# Generated by Django 5.0.6 on 2024-06-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_tipoproducto_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'ordering': ['id'], 'verbose_name': 'tipo de producto', 'verbose_name_plural': 'tipo de productos'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
