# Generated by Django 5.0.6 on 2024-06-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_tipoproducto_options_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado de Vehiculo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'estado de vehiculo',
                'verbose_name_plural': 'estado de vehiculos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Vehiculo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'tipo de vehiculo',
                'verbose_name_plural': 'tipo de vehiculos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['proveedor'], 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='Rut'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idVehiculo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('color', models.CharField(max_length=12, verbose_name='Color de Vehiculo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.estado', verbose_name='Estado de Vehiculo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tipovehiculo', verbose_name='Tipo de Vehiculo')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'ordering': ['nombre'],
            },
        ),
    ]
