# Generated by Django 5.0.6 on 2024-06-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_rename_estado_estadovehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='transportista',
            options={'ordering': ['nombre'], 'verbose_name': 'transportista', 'verbose_name_plural': 'transportistas'},
        ),
        migrations.AddField(
            model_name='transportista',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transportista', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo', verbose_name='Imagen'),
        ),
    ]
