# Generated by Django 5.0.4 on 2024-06-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_rename_estado_estadovehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
