# Generated by Django 5.0.4 on 2024-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_producto_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='value',
            field=models.IntegerField(verbose_name='Valor'),
        ),
    ]
