# Generated by Django 5.0.6 on 2024-07-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_cliente_alter_transportista_options_and_more'),
        ('crud', '0007_alter_producto_value'),
    ]

    operations = [
    ]
