# Generated by Django 5.0.4 on 2024-07-03 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_merge_20240702_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_peso', models.CharField(max_length=50, verbose_name='Tipo de Peso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_peso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.tipopeso', verbose_name='Tipo de Peso'),
        ),
    ]
