# Generated by Django 5.0.6 on 2024-07-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_merge_20240701_2231'),
        ('crud', '0009_tipopeso_producto_peso_producto_tipo_peso'),
    ]

    operations = [
    ]
