# Generated by Django 5.0.6 on 2024-07-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_merge_20240703_0024'),
        ('crud', '0010_merge_20240703_0849'),
    ]

    operations = [
    ]
